<?php

namespace Jazzyweb\AcmeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenciaRepository extends EntityRepository
{
}
